# -*- coding: utf-8 -*-
"""Robotic _Automation_Factory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ACIAHfYgA3djY9bKY2GFDgC_xkL8uDFd
"""



def sort(width, height, length, mass):
    """
    Determines the stack for a package based on its dimensions and mass.

    Parameters:
    - width (float): Width of the package in cm.
    - height (float): Height of the package in cm.
    - length (float): Length of the package in cm.
    - mass (float): Mass of the package in kg.

    Returns:
    - str: The name of the stack ("STANDARD", "SPECIAL", or "REJECTED").
    """
    # Calculate volume and determine bulky criteria
    volume = width * height * length
    is_bulky = volume >= 1_000_000 or max(width, height, length) >= 150

    # Determine heavy criteria
    is_heavy = mass >= 20

    # Dispatch package based on criteria
    if is_bulky and is_heavy:
        return "REJECTED"
    elif is_bulky or is_heavy:
        return "SPECIAL"
    else:
        return "STANDARD"

sort(90,80,70,15)

sort(100,100,120,24)

sort(100,100,90,56)

sort(100,100,120,12)